version: "3.7"

services: 
  node-red: 
    image: nodered/node-red:latest
    ports: 
      - "1880:1880"
    volumes:
      - node-red-data:/data
      
  main:
    image: main 
    ports: 
      - "80:8080"

volumes:
  node-red-data: